package:
  name: instant
  version: "1.4.0"

source:
  fn: instant-1.4.0.tar.gz
  url: https://bitbucket.org/fenics-project/instant/downloads/instant-1.4.0.tar.gz
  md5: e6fa58eb5df4401aac8542110dc1d220

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - numpy <1.9
    - cmake
    - swig

test:
  imports:
    - instant

  commands:
    - instant-clean
    - instant-showcache

  requires:
    - nose

about:
  home: http://www.fenicsproject.org
  license: BSD License or The GNU Lesser General Public License, version 3.0
  summary: 'Instant Inlining of C/C++ in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
