package:
  name: petsc4py
  version: "3.4"

source:
  fn: maint-3.4.zip
  url: https://bitbucket.org/petsc/petsc4py/get/maint-3.4.zip
  sha1: a4ed6bc295d61dbe73817fcb423f33548c72e8f2

build:
  number: 1

requirements:
  build:
    - python
    - mkl
    - numpy <1.9
    - cython
    - petsc ==3.4.5

  run:
    - python
    - petsc ==3.4.5

test:
  imports:
    - petsc4py
    - petsc4py.lib

  requires:
    - mkl

about:
  home: https://bitbucket.org/petsc/petsc4py/
  license: BSD License
  summary: 'PETSc for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
